name: Emin_Full_Auto
on:
  push:
    paths: [ 'linkler.json' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Botu Calistir
        run: python updater.py
      - name: Eklentiyi Pisir
        run: |
          chmod +x gradlew
          ./gradlew make
      - name: Kaydet ve Gonder
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "EminBot"
          git add .
          git commit -m "Otomatik Guncelleme Tamam" || echo "Degisiklik yok"
          git push --force origin master # Zorla gonder, cakismayi ez
